### ISSUE TITLE
template_id with smtp ActionMailer::Base

### ISSUE THREAD

**Issue by alexey** [sendinblue/APIv3-ruby-library#16]
Hello guys, 

I am trying to pass in template_id with transactional email that is send from my email class 
```
mail to: email, subject: subject, template_id: '14'
```

Can i reuse default ActionMailer to send email with template id ?
[Like this one](https://github.com/sendinblue/APIv3-ruby-library/blob/40edcc3f1142665526e48517df74f0167fb76516/docs/SendSmtpEmail.md)

**Comment by alexey** [comment]
anyone ?

**Comment by demitriousj** [comment]
Would probably need to see the whole class

**Comment by devaudrius** [comment]
I believe the key has to be camelCased -> `templateId`

**Comment by aakanksha-sib** [comment]
Thats correct @devaudrius !
Thanks :)
