### ISSUE TITLE
Minimum version for gem 'json'

### ISSUE THREAD

**Issue by viktor-shmigol** [sendinblue/APIv3-ruby-library#33]
Hello guys,
We are going to use your sdk in our project.
We got an error while installing this gem:
```
Bundler could not find compatible versions for gem "json":
  In snapshot (Gemfile.lock):
    json (= 1.8.6)

  In Gemfile:
    dm-serializer was resolved to 1.2.2, which depends on
      json (~> 1.6)

    sib-api-v3-sdk was resolved to 5.2.4, which depends on
      json (>= 2.1.0, ~> 2.1)

```
We have few gems which depends on  json (~> 1.6). So, it's hard to us to update them.
I've create PR for it. Could you please take a look at https://github.com/sendinblue/APIv3-ruby-library/pull/32

**Comment by aakanksha-sib** [comment]
Hi @viktor-shmigol ,
Due to security issues, we will not be able to lower the supported version.
We suggest you please try upgrading at your end.

Thanks!
Aakanksha
