### ISSUE TITLE
Snakecase doesn't work, have to use camelcase

### ISSUE THREAD

**Issue by martyciz** [sendinblue/APIv3-ruby-library#35]
Using snakecase for API attributes written in documentation doesn't seem to work. We have to send options in camelcase to match REST API.

Simple example for [create_contact](https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/CreateContact.md) - this doesn't work:
```ruby
SibApiV3Sdk::ContactsApi.new.create_contact(
  email: email,
  list_ids: [list_id],
  update_enabled: true,
)
```

While this works:
```ruby
SibApiV3Sdk::ContactsApi.new.create_contact(
  email: email,
  listIds: [list_id],
  updateEnabled: true,
)
```

**Comment by martyciz** [comment]
relates with https://github.com/sendinblue/APIv3-ruby-library/pull/20/commits/3a0bb8e0216ac4442b36b47a1decee337e633681

**Comment by peteoleary** [comment]
Same problem with SibApiV3Sdk::SendSmtpEmail, template_id needs to be templateId

**Comment by aakanksha-sib** [comment]
Hi @martyciz , @peteoleary 
The variables are to be passed in camelCase. Please check the `recommendation` section on the home page https://github.com/sendinblue/APIv3-ruby-library

```
Please follow camelCase convention for variables in the API's. For example, use customVariable instead of custom_variable.
```

Also, a few examples can be found here as well:
https://developers.sendinblue.com/docs/synchronise-contact-lists

**Comment by Thrry** [comment]
Would be great to have this recommandation on top of the page.

**Comment by kirylpl** [comment]
@aakanksha-sib Could you update docs please? https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/CreateContact.md
