### ISSUE TITLE
Unable to assign new contact to list using create_contact method

### ISSUE THREAD

**Issue by jwilson114** [sendinblue/APIv3-ruby-library#36]
```
def create
  sib = SibApiV3Sdk::ContactsApi.new
  contact = Contact.new(contact_params)
  return render_error unless contact.valid?
  begin
    result = sib.create_contact(email: contact.email, attributes: { COUNTRY: contact.country }, list_ids: [5], update_enabled: true)
  rescue SibApiV3Sdk::ApiError => e
    puts e
  end
end
```

Using the above the code I am unable to assign a new contact to a list with id: 5. But the contact is added to the global contact list, and a contact ID is returned from the API.

Please can you advise. Thanks

**Comment by jwilson114** [comment]
same as https://github.com/sendinblue/APIv3-ruby-library/issues/35

**Comment by kirylpl** [comment]
`SibApiV3Sdk::CreateContact` seems to utilize camelCase attributes only so docs are wrong
https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/CreateContact.md

**Comment by aakanksha-sib** [comment]
Hi @jwilson114 ,
Please use the variables in camel case only.
You can check the https://github.com/sendinblue/APIv3-ruby-library#recommendation section on the home page.

Thanks!
Aakanksha
