### ISSUE TITLE
Cannot find a way to send bulk personalized emails

### ISSUE THREAD

**Issue by vikas-wadhwa** [sendinblue/APIv3-ruby-library#37]
New to the platform and API; we're trying to send a bulk template to ~10,000 users, each recipient personalized with params.

It seems SibApiV3Sdk::SMTPApi#send_transac_email is only capable of one recipient and/or params object at a time?

And the same goes for SibApiV3Sdk::EmailCampaignsApi#send_email_campaign_now. It can take multiple recipients but only a single params object? So I cannot send to multiple people, the same template, personalized for each of them?

**Comment by aakanksha-sib** [comment]
Hi @vikas-wadhwa ,
You can send mail using `send_transac_email` maximum upto 99 recipients at a time which includes your `to`, `cc` and `bcc` email addresses.

However if your mail sending is so much more and frequent, you can use SMTP relay. The corresponding documentation can be found on the `SMTP & API` section on your sendinblue account dashboard.
Thanks!

**Comment by RedskyThirty** [comment]
> New to the platform and API; we're trying to send a bulk template to ~10,000 users, each recipient personalized with params.
> 
> It seems SibApiV3Sdk::SMTPApi#send_transac_email is only capable of one recipient and/or params object at a time?
> 
> And the same goes for SibApiV3Sdk::EmailCampaignsApi#send_email_campaign_now. It can take multiple recipients but only a single params object? So I cannot send to multiple people, the same template, personalized for each of them?

Hello, have you found a solution? SendGrid allows to send emails to multiple recipients based on an unique html source but for each recipient a set of personalized data. I don't find any way to do that with the SendinBlue API :-(
We have to make a call to the API for each recipient???

**Comment by mourraille** [comment]
Hello @RedskyThirty , we are at the moment working on a solution to have this available through the API. It should be possible soon. Thanks for your feedback!

**Comment by Lexe003** [comment]
Is it available?

**Comment by RedskyThirty** [comment]
> @mourraille Is it available?

No time to check yet but Mauricio from Sendinblue said me that yes ;-)

**Comment by mourraille** [comment]
The endpoint is now publicly available [through our beta program](https://developers.sendinblue.com/docs/batch-send-transactional-emails). The feature should come soon to the API wrappers.
