### ISSUE TITLE
URI.escape is obsolete (Ruby 2.7)

### ISSUE THREAD

**Issue by renchap** [sendinblue/APIv3-ruby-library#47]
In Ruby 2.7, `URI.escape` (aliased as `URI.encode`) is marked as obsolete and displays a warning:

```
/Users/renchap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sib-api-v3-sdk-7.1.0/lib/sib-api-v3-sdk/configuration.rb:178: warning: URI.escape is obsolete
/Users/renchap/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/sib-api-v3-sdk-7.1.0/lib/sib-api-v3-sdk/api_client.rb:267: warning: URI.escape is obsolete
```

This method has been marked as deprecated for a long time and will be removed in Ruby 3.0.

There are several ways to replace it, depending on the result you want (`URI.escape` behaviour was wrong when handling certain characters, like spaces).

For example you can use `URI.encode_www_form_component(string)` but this will replace spaces with `+`. So you could also do `URI.encode_www_form_component(string).gsub('+', '%20')`.
Another way is to use the `addressable` gem. See for example https://github.com/docusign/docusign-ruby-client/issues/45#issuecomment-648107234

**Comment by aakanksha-sib** [comment]
Thanks @renchap  for pointing this out. We will look into this and get back to you shortly!
- Aakanksha

**Comment by abepark01** [comment]
Any updates on this? 
We are running ruby 3.0 and getting the error `undefined method `encode' for URI:Module`

**Comment by xbra** [comment]
I get more than a warning, I get a **`NoMethodError`**.

`…/gems/sib-api-v3-sdk-7.3.0/lib/sib-api-v3-sdk/configuration.rb:178:in 'base_url': undefined method 'encode' for URI:Module (NoMethodError)`

@aakanksha-sib, help is needed soon.

Thanks in advance.
Max


```
$ gem list sib-api-v3-sdk
*** LOCAL GEMS ***
sib-api-v3-sdk (7.3.0, 5.3.0, 5.2.5)
```

```
$ ruby --version
ruby 2.7.2p137 (2020-10-01 revision 5445e04352) [x86_64-linux]
```

**Comment by aakanksha-sib** [comment]
Hi @renchap @xbra ,
Sorry for the delayed response. We will be sending a fix within 2-3 working days.

**Comment by aakanksha-sib** [comment]
This issue has now been fixed in the latest version https://github.com/sendinblue/APIv3-ruby-library/releases/tag/v7.4.0
Thanks !
