### ISSUE TITLE
New "sort" param for GetEmailEventReport

### ISSUE THREAD

**Issue by brilnius** [sendinblue/APIv3-ruby-library#48]
Hello.

(I take the opportunity to emphasize the quality of code and documentation here. :-)

It seems that a "sort" query parameter was added recently for GetEmailEventReport :
https://developers.sendinblue.com/reference#getemaileventreport-1

> sort (string) = asc | desc
> Sort the results in the ascending/descending order of record creation

Do you plan to also add that parameter in the SDK ?
https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/GetEmailEventReportEvents.md

BTW, the API change breaks compatibility: the default is now to return events in "most recent first" order. Unless we get this parameter very soon, we will have to change our code substantially.

**Comment by aakanksha-sib** [comment]
Hi @brilnius ,
This feature shall be available with the SDK latest by next week!
Thanks!
