### ISSUE TITLE
GetEmailCampaign with empty recipients and statistics

### ISSUE THREAD

**Issue by xbra** [sendinblue/APIv3-ruby-library#54]
Hi all, if I am calling [`get_email_campaign()`](https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/EmailCampaignsApi.md#get_email_campaign) I am expecting an instance of [`GetEmailCampaign`](https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/GetEmailCampaign.md) with `recipients` and `statistics`. According to the mentioned docs these should be of type [`GetSmsCampaignRecipients`](https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/GetSmsCampaignRecipients.md), which has no properties at all. Before, it had a property `lists`, which was an array of list ids associated with the campaign.

Where do I get an array of list ids from?

**Comment by maxbraeutigam** [comment]
@aakanksha-sib – can I please get an answer?

**Comment by aakanksha-sib** [comment]
Hi @xbra @maxbraeutigam ,
We are looking  into this and we will get back to you on this issue ASAP.

**Comment by maxbraeutigam** [comment]
@aakanksha-sib – can I please get an answer?

**Comment by aakanksha-sib** [comment]
Hi @maxbraeutigam ,
Sorry for the delay.
Can you please help me understand the problem statement a little better ?
Are you not receiving `statistics` and `recipients`  in the response of `get_email_campaign` ?
If you have not attached any lists to your campaign so far, it is an expected response. Also, statistics will be present once the campaign is actually sent. Which in turn needs the campaign to be scheduled.
If you still have doubts regarding the same, please raise a ticket from the account that you are facing issue with along with the campaign id for which you are having the trouble.
Thanks!
Aakanksha

**Comment by maxbraeutigam** [comment]
Hi @aakanksha-sib - exacly `recipients` and `statistics` are always an emtpy object of type `GetSmsCampaignRecipients`. For example:

```
--- GetEmailCampaign
id: 240
name: …
sent_date: '2021-05-04T06:04:38.000+02:00'
recipients: GetSmsCampaignRecipients {}
statistics: GetSmsCampaignRecipients {}
```

But also have a look here: The documentation of [`GetSmsCampaignRecipients`](https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/GetSmsCampaignRecipients.md) does not list any properties at all.

With APIv3-nodejs-library I can see the lists and statistics:

```
exports {
  id: 240,
  …
  recipients: { lists: [ 6 ], exclusionLists: [] },
  statistics: {
    globalStats: {
      uniqueClicks: 112,
      …
    },
    campaignStats: [ [Object] ],
    mirrorClick: 8,
    remaining: 0,
    linksStats: {
      'https://www.…': 12,…
    },
    statsByDomain: {
      'web.de': [Object], …
    },
    statsByDevice: { desktop: [Object], mobile: [Object], tablet: [Object] },
    statsByBrowser: { … }
  },
  sentDate: 2021-05-04T04:04:38.000Z
}
```

Why did you close the bug? Nothing is solved at all!

**Comment by maxbraeutigam** [comment]
@aakanksha-sib - it’s really embarrassing what’s happening here!
