### ISSUE TITLE
mailer is not testable

### ISSUE THREAD

**Issue by aka47** [sendinblue/APIv3-ruby-library#56]
we want to use sendinblue for our new rails project. But we can not find any way to test our code using this gem. Looking at https://github.com/postageapp/postageapp-ruby the integration into ActionMailer is very different. Postageapp gives keeps the rails interface working and we can test the code. 

```
class UserMailer < ApplicationMailer

  def invitation_instructions(record, token, opts={})
    @sendinblue = SibApiV3Sdk::TransactionalEmailsApi.new
    @email.subject = "You are invited to Elloworks"
    @sendinblue.send_transac_email(@email)
  end
```
With sendinblue we are not able to test any of the mailings we send out - so sending out emails could break with any release without us knowing about it. Did we miss anything? Can you help us out? If we use smtp it is fine - but we wanted to use the API and templates managed in sendinblue.

**Comment by aakanksha-sib** [comment]
Hi @aka47 ,
Please try with the ruby specific example shared over here: https://developers.sendinblue.com/docs/send-a-transactional-email for testing the transactional emails api.
Let us know in case you still encounter any issue.

Thanks!

**Comment by maysam** [comment]
@aakanksha-sib you should one of your developers to look into this, he's not talking about testing emails
