### ISSUE TITLE
You need to install gem addressable

### ISSUE THREAD

**Issue by VincentSim** [sendinblue/APIv3-ruby-library#57]
Hi there
 In your `api_client.rb` you are calling 
```ruby
require 'addressable/uri'
```
but there is no dependecy declared

I had to install addressable by my side.

**Comment by aakanksha-sib** [comment]
Hi @VincentSim ,
We will check and update this. Thanks :)

**Comment by aakanksha-sib** [comment]
Hi @VincentSim ,
We will check and update this. Thanks :)
