### ISSUE TITLE
getting same email twice via send_transac_email

### ISSUE THREAD

**Issue by PyrinAndrii** [sendinblue/APIv3-ruby-library#59]
I use `gem 'sib-api-v3-sdk', '~> 7.1.0'` & `ruby 2.7.2`.

Have a problem with sending emails. When I use `SibApiV3Sdk::TransactionalEmailsApi.new.send_transac_email(@email)` then same email is sent twice.

![Screenshot 2021-07-02 at 13 43 09](https://user-images.githubusercontent.com/43855653/124263211-a43dd080-db3b-11eb-9656-0dba677cdaa5.png)
![Screenshot 2021-07-02 at 12 57 54](https://user-images.githubusercontent.com/43855653/124260301-33e18000-db38-11eb-9e37-40b586197efb.png)

It is happening on stage env, and only via a cron task (use whenever gem, the task is running every 5 minutes). Can't reproduce it locally (works as expected), when run it with `rake mailing:send_timed_reminders` on stage works fine as well (sends only 1 email)

I put `puts` before `SibApiV3Sdk::TransactionalEmailsApi.new.send_transac_email(@email)` and here on the screen is proof that code was run only once, but on the screenshots above you can see 2 emails were sent.
![Screenshot 2021-07-02 at 13 21 23](https://user-images.githubusercontent.com/43855653/124260673-9fc3e880-db38-11eb-865a-c023afc6cc84.png)

 Does anyone have an idea why is it happening? thanks for the help in advance)

**Comment by aakanksha-sib** [comment]
Hi @PyrinAndrii ,
Please raise a support request from your official account. 
Please mention the message-id/request inputs/request date time for which the issue occurred. We will further check why are you facing the issue.
Thanks!
