### ISSUE TITLE
Better Errors

### ISSUE THREAD

**Issue by AndreVolpi** [sendinblue/APIv3-ruby-library#60]
Currently when there is an error with the API request, the gem just returns `Bad request`, would be nice to receive the same message as when we send the same request by CURL (usually states what is wrong, be it a missing parameter or something else).

**Comment by Ruff9** [comment]
I currently get `Bad request` randomly on some of the calls to the API, and it's kind of hard to debug with that little information.

**Comment by JensC** [comment]
Updating to 8.1.0 still only produces a Bad request without further info!

**Comment by silentshade** [comment]
@JensC I had the same problem. It appears you should set `config.debugging = true` to get full error. Hope it helps.

**Comment by NagendraSIB** [comment]
Hi @JensC 
Hope issue has been resolved after @silentshade comment.
Thanks
