### ISSUE TITLE
Multiple Reply To

### ISSUE THREAD

**Issue by germanoatrg** [sendinblue/APIv3-ruby-library#61]
**Is there a way to have multiple reply_to?**

Using SendInBlue with Rails ActionMailer allows to set up multiple reply_to emails
`mail(to: "mail1@email.com", subject: "Subject", message: "Message", reply_to: ["mail2@email.com", "mail3@email.com"])`

However, when using the SendInBlue API I can only set one
https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/SendSmtpEmailReplyTo.md

From https://www.rfc-editor.org/rfc/rfc5322#section-3.6.2
> In either case, an optional reply-to field MAY also be included, which contains the field name "Reply-To" and a comma-separated list of one or more addresses.

**Comment by NagendraSIB** [comment]
Hi @germanoatrg 
Please update it to the latest version 8.1.0.
Thanks
