### ISSUE TITLE
New event type loadedByProxy is filtered out

### ISSUE THREAD

**Issue by brilnius** [sendinblue/APIv3-ruby-library#63]
A few days ago the SIB API v3 was modified to provide a new event type "loadedByProxy".
However these events are filtered out by the Ruby SDK when using e.g. :
SibApiV3Sdk::TransactionalEmailsApi#get_email_event_report()

By the way I suggest that the list of event types relevant for emails could be "factorized" somewhere in the SDK, instead of being repeated in multiple methods (DRY principle).

**Comment by Ergofy** [comment]
I'm getting runtime errors due to 'loadedByProxy' not being filtered out. Do you know when/which commit this changed?

![image](https://user-images.githubusercontent.com/24555489/155978391-dc0200ec-505e-4cc7-9fad-f114f827c22d.png)

**Comment by NagendraSIB** [comment]
Hi @brilnius 
Please update it to the latest version 8.1.0.
Thanks
