### ISSUE TITLE
API returning "loadedByProxy" events which breaks API client code

### ISSUE THREAD

**Issue by Ergofy** [sendinblue/APIv3-ruby-library#64]
The API has started returning an event type called "loadedByProxy" which causes runtime errors. This happens in versions 7.1.0 and 8.0.0.

![image](https://user-images.githubusercontent.com/24555489/155980090-ce76ad8c-b8ae-473f-bc1a-6e0f1e51460a.png)

**Comment by NagendraSIB** [comment]
Hi @Ergofy 
Please update it to the latest version 8.1.0.
Thanks

**Comment by Ergofy** [comment]
Fixed, thanks!
