### ISSUE TITLE
Bad documentation error

### ISSUE THREAD

**Issue by JensC** [sendinblue/APIv3-ruby-library#66]
Hi,

You really should take care about your documentation (along with better error descriptions). The following cost me and my employer 2 working days.

Under send_transac_email the api call wants an object SibApiV3Sdk::SendSmtpEmail.
Since I wanted to use a predefined template I added as the documentation states template_id. But that is the wrong key. It wants templateId.

**Comment by NagendraSIB** [comment]
Hi @JensC 
Can you pls share the error & also for which route getting it. If possible pls share when you are getting that like code snap.
Thanks

**Comment by JensC** [comment]
https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/SendSmtpEmail.md if I remember right, it was here.

**Comment by NagendraSIB** [comment]
For code example pls follow this - https://developers.sendinblue.com/reference/sendtransacemail
