### ISSUE TITLE
params for a template

### ISSUE THREAD

**Issue by JensC** [sendinblue/APIv3-ruby-library#67]
Hello again,

I noticed another difference between v2 and v3 api. If you define a HTML template and you pass some params (send_transac_email) via api to it, in version 2 it was possible to send html in these params to the template, which was very useful. In v3 however the html-params gets insert as text.

**Comment by NagendraSIB** [comment]
Hi @JensC 
v2 is now deprecated kindly use v3 as per the defined format.
thanks

**Comment by JensC** [comment]
I was hoping that v3 is able to do at least as much as v2.

**Comment by NagendraSIB** [comment]
Please follow this for more details - https://developers.sendinblue.com/docs/migration-guide-for-api-v2-users-1
