### ISSUE TITLE
Date type regression since 7.4.0

### ISSUE THREAD

**Issue by brilnius** [sendinblue/APIv3-ruby-library#68]
Hello.

When using this code:
```
sib = SibApiV3Sdk::TransactionalEmailsApi.new
resp = sib.get_email_event_report(...etc...)
date = resp.events.first.date
[date, date.class]
```

With version 7.3 the result was:
`[Mon, 07 Mar 2022 16:53:41 +0100, DateTime]`
The SDK provided a DateTime object as event date.

Starting with version 7.4 the result is:
`["2022-03-07T16:53:41.137+01:00", String]`
The SDK now provides a String as event date, in ISO-8601 format (also used in JSON I think).

We discovered this regression while upgrading to version 8.1.0 for "loaded by proxy" event type support. And then found the changing gem version by trying gem versions one by one.

From a SDK in my opinion we expect ready-to-use objects like DateTime, not Strings we need to parse first.

**Comment by NagendraSIB** [comment]
HI @brilnius 
Due to some internal functionality, we are doing it.
Thanks
