### ISSUE TITLE
Version 9.1.0 has lot of undocumented breaking changes

### ISSUE THREAD

**Issue by fabn** [sendinblue/APIv3-ruby-library#72]
e.g.

* `SibApiV3Sdk::ListsApi` is gone
* `SibApiV3Sdk::AttributesApi` is gone

Also you don't provide a changelog so it's pretty hard to upgrade.

WDYT?

**Comment by NagendraSIB** [comment]
HI @fabn 
We have removed the unnecessary doc as you mentioned.
Here is the link for changelog https://github.com/sendinblue/APIv3-ruby-library/compare/v9.0.0...v9.1.0

**Comment by fabn** [comment]
Yes but that's not a changelog, it's a git diff that's pretty hard to read. Also since I was using those classes in my code now I have to rewrite my code (with what replacements? Usually a changelog states this, don't use xxx instead use yyy)

Finally if some API have been removed SDK version should be bumped to 10.x it's the base of semver 😉

**Comment by NagendraSIB** [comment]
Hi @fabn 
Can you please upgrade to our new ruby SDK https://github.com/getbrevo/brevo-ruby

Thanks
