### ISSUE TITLE
GetExtendedCampaignStatsGlobalStats has no attributes

### ISSUE THREAD

**Issue by yenshirak** [sendinblue/APIv3-ruby-library#75]
GetExtendedCampaignStatsGlobalStats has no attributes so it isn't possible to get the global email campaign stats: https://github.com/sendinblue/APIv3-ruby-library/blob/master/lib/sib-api-v3-sdk/models/get_extended_campaign_stats_global_stats.rb#L19

**Comment by NagendraSIB** [comment]
Hi @yenshirak  
Can you please upgrade to our new ruby SDK https://github.com/getbrevo/brevo-ruby

Thanks
