### ISSUE TITLE
Implement list_invalid_properties and valid?

### ISSUE THREAD

**Issue by aaronkelton** [sendinblue/APIv3-ruby-library#76]
Hi, I'm looking at these docs and noticed `list_invalid_attributes` simply returns a new array, and `valid?` simply returns `true`. Is there a plan to implement these methods? If not, may I open a PR to implement them?

https://github.com/sendinblue/APIv3-ruby-library/blob/master/lib/sib-api-v3-sdk/models/send_smtp_email.rb#L192-L203

**Comment by NagendraSIB** [comment]
Hi @aaronkelton 
Can you please upgrade to our new ruby SDK https://github.com/getbrevo/brevo-ruby

Thanks
