### ISSUE TITLE
Fix code or documentation for html_content or htmlContent

### ISSUE THREAD

**Issue by aaronkelton** [sendinblue/APIv3-ruby-library#77]
I noticed today when trying to get my app to use the API that `html_content` was `nil`. I had to switch to the camel case property to get it to work. Could you please update the documentation to show camel case?

The code shows that [it checks for camel cased keys](https://github.com/sendinblue/APIv3-ruby-library/blob/master/lib/sib-api-v3-sdk/models/send_smtp_email.rb#L137), but the [documentation shows `html_content` as underscore](https://github.com/sendinblue/APIv3-ruby-library/blob/master/docs/SendSmtpEmail.md) case.

**Comment by NagendraSIB** [comment]
Hi @aaronkelton 
Can you please upgrade to our new ruby SDK https://github.com/getbrevo/brevo-ruby

Thanks
