### ISSUE TITLE
SSL peer certificate or SSH remote key was not OK

### ISSUE THREAD

**Issue by RageCrezz** [sendinblue/APIv3-ruby-library#78]
Hello Brevo-Team,

I am trying to configure the api_instance according to the guide in the README.md and receive following error:
`SSL peer certificate or SSH remote key was not OK`

I am providing the correct API key and even pass it as a direct string to `config.api_key['api-key']`, though I am still receiving the error above.

This is my code in Ruby:
```
require 'sib-api-v3-sdk'

SibApiV3Sdk.configure do |config|
  config.api_key['api-key'] = ENV["BREVO_API"]
end

api_instance = SibApiV3Sdk::AccountApi.new

begin
  result = api_instance.get_account
  p result
rescue SibApiV3Sdk::ApiError => e
  puts "#{e}"
end
```

It would be nice to know what exactly I am doing wrong. Thank you in advance.

PS: It seems I can't label my own issue, sorry about that.

**Comment by NagendraSIB** [comment]
Already in discussion [here](https://github.com/getbrevo/brevo-ruby/issues/2#issuecomment-2120042452), so I'm closing this
