### ISSUE TITLE
Speed up Gem load time

### ISSUE THREAD

**Issue by adrienpoly** [sendinblue/APIv3-ruby-library#79]
Hello

When I run [bumbler](https://github.com/nevir/Bumbler) (bumbler --all) SIB is by fare the slowest gem to load. 
This is slowing down every rails s / rails c commands

Is there a way to speed up this loading time ?
I only need a few methods from this gem, is there a way to require only a few API routes? (I tried but didn't succeeded)

Thanks

**Comment by NagendraSIB** [comment]
Hi @adrienpoly 
Can you please try our new ruby SDK  https://github.com/getbrevo/brevo-ruby 

Thanks
