### ISSUE TITLE
Should I use this gem or brevo-ruby

### ISSUE THREAD

**Issue by adrienpoly** [sendinblue/APIv3-ruby-library#80]
It is unclear to me if I should keep using this gem or migrate to https://github.com/getbrevo/brevo-ruby

**Comment by NagendraSIB** [comment]
@adrienpoly please migrate to [brevo-ruby](https://github.com/getbrevo/brevo-ruby)

**Comment by adrienpoly** [comment]
would it be possible to archive this repo then and put a clear message in the read me?
